# Workflow syntax:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# The name of the workflow as it will appear in the "Actions" tab of the GitHub repository.
name: PSScriptAnalyzer

# Specifies the trigger for this workflow.
on: [workflow_dispatch]

# Groups together all the jobs that run.
jobs:
  # Job ID, a unique string identifier for the job.
  analyze:
    # A name for the job, which is displayed in the GitHub UI.
    name: Run PSScriptAnalyzer
    # Define the type of machine to run the job on.
    runs-on: windows-2022
    # Groups together all the steps that run in this job ID
    steps:
      # Specifies that this step will run v3 of the actions/checkout action
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Checkout code
        uses: actions/checkout@v3

      # PSScriptAnalyzer custom action
      - name: Run PSScriptAnalyzer
        # Used to tell GitHub which action you want to use
        # The specified path and branch needs to have action.yml file
        uses: metablaster/WindowsFirewallRuleset/Actions/PSScriptAnalyzer@develop
        # Initialize settings declared in action.yml
        with:
          path: .\
          recurse: true
          settings: Config/PSScriptAnalyzerSettings.psd1
